### ISSUE TITLE
Make sure we update the GA UA

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#153]
Seems like we forgot to update [this](https://github.com/mozilla/mozfest-schedule-app/blob/gh-pages/index.html#L17) when we forked the app from [SRCCON's](https://github.com/OpenNews/srccon-schedule/blob/gh-pages/index.html#L20)

**Comment by mmmavis** [comment]
/cc @edrushka 
not sure where I should be putting this. Is there a todo list for 2016's app?

**Comment by edrushka** [comment]
@ScottDowne did you create a new repo for the schedule app when you worked on it for Hive Chicago Buzz? If so, I can start a to-do list there @mmmavis (although I'll probably need a bit of help as I only know the broad strokes).

**Comment by ScottDowne** [comment]
@edrushka Yeah, I created a generic repo https://github.com/mozilla/mofo-schedule-app

Idea was to eventually put all apps in there, including this one. Not sure when and if that'll happen though.

**Comment by mmmavis** [comment]
this is now unblocked.
