### ISSUE TITLE
Ungroup Category and Location

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mozfest-event-app#197]
For Mozfest we have "Spaces" which are like a category, one per session. Spaces at Mozfest are linked to Location. For other events, this might not be the case. Let's consider separating these two bits of meta data. 

Consider it, but don't assume it's the right idea or necessary.

<img width="408" alt="screenshot 2016-05-02 12 19 39" src="https://cloud.githubusercontent.com/assets/53411/14959958/2969821a-1060-11e6-91ed-aa7eefce76c2.png">

**Comment by kristinashu** [comment]
I don't think we use category anymore so this is no longer an issue. Please reopen if needed.
