### ISSUE TITLE
Clarify workflow between spreadsheet, github, staff, and wranglers

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mozfest-event-app#238]
Let's summarize the workflow for each edits, updates, delete. Who does what, where, when, and how.

**Comment by xmatthewx** [comment]
Goal: lock the spreadsheet used to populate the app. Give absolute minimum number of people access. To reduce opportunities for mistakes and bugs and extra effort.

**Comment by xmatthewx** [comment]
@mmmavis – do you have a link to the schedule we created in etherpad with @Saallen?

I'd like us to create milestones in this repo with epics to reflect that timeline. Then we can move our design and dev issues out of the backlog based on when we expect to do that work.

**Comment by mmmavis** [comment]
hey @xmatthewx you mean this one? https://public.etherpad-mozilla.org/p/2016-mozfest-event-app

**Comment by xmatthewx** [comment]
Yep! @edrushka that pad has an outline of when move from github to spreadsheet, when we lock spreadsheet and go to app, etc.

**Comment by edrushka** [comment]
Thanks @xmatthewx - please be advised that a Sept 28 deadline (line 17 in the etherpad) has panicked some of the Space Wranglers. Do all spaces need to be ported at once, or can we give some spaces a few days extension?

**Comment by mmmavis** [comment]
Hey @edrushka yes all sessions will be ported at once. How many days are we thinking about postponing the Sept 28 deadline to?

After things have been transferred to the event app spreadsheet wranglers can still make changes - just that facilitators won't have access to the spreadsheet and that spreadsheet's editing interface is not as good as Github's.

Is the 29th Sept – 7th Oct timeframe (line 25: https://public.etherpad-mozilla.org/p/2016-mozfest-event-app ) enough time for wranglers to lock data on the spreadsheet? If not we should revisit the milestones and deadlines we set.

I'll create Github milestones and tickets based on the Etherpad notes today. That should make organizing things easier. 😄

**Comment by edrushka** [comment]
@Saallen have you heard any more feedback from the wranglers on this? I know it's a tight timeline, but I feel like we need to push if we want the schedule to be a more useful tool this year.

**Comment by Saallen** [comment]
I have 50% 50% split. I want to email dilemma and badges individually to
quell their fears and to understand them. Hope to have a more unified
decision by mid Wed if that is not messaging with timelines too much?

**Comment by mmmavis** [comment]
Hi all, I created 3 milestones: https://github.com/mozilla/mozfest-event-app/milestones (step 1-3) based on the Etherpad. I will be creating tickets for each milestone. If the timeline seems too tight we can adjust due dates for each milestone accordingly.

**Comment by edrushka** [comment]
Good news: we spoke with the spaces who had concerns and reassured them. We can work towards our original deadline of Sept 28.

**Comment by mmmavis** [comment]
This has been sorted out! 🍻  Spreadsheet is now locked. Any further changes will be made by the MozFest program team (Dan will be the primary contact for this 😄).
