### ISSUE TITLE
Figure out deployment process

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#248]
This includes 
- [x] which repo to use
- [x] set up staging instance (https://github.com/MozillaFoundation/mofo-devops/issues/414)
- [x] set up production instance (https://github.com/MozillaFoundation/mofo-devops/issues/415)
- [x] adapt to GitHub flow?

**Comment by mmmavis** [comment]
@cadecairos can you help check which repo https://app.mozillafestival.org/ is based on? I thought it being https://github.com/mozilla/mozfest-schedule-app but the [GitHub page of that repo](http://mozilla.github.io/mozfest-schedule-app/) doesn't look like 2015's schedule app...  Is content on https://app.mozillafestival.org/ cached?

**Comment by mmmavis** [comment]
pinging @cadecairos again in case you missed the notification last week 😉

**Comment by cadecairos** [comment]
> can you help check which repo https://app.mozillafestival.org/ is based on?

it looks like it's https://github.com/mozilla/schedule-app-core/tree/backup-2015-mozfest-app or at least a commit based on it.

**Comment by mmmavis** [comment]
@cadecairos  I'm thinking to set up staging like what we did for Network Pulse - push to `master` triggers push to S3 (mozfest-event-app.mofostaging.net ?).  What do you think? I can open up a separate devops ticket if you like. 😃 

/cc @xmatthewx @kristinashu

**Comment by cadecairos** [comment]
@mmmavis that sounds perfect! 

We'll also need to figure out how to do production deployments to S3. I'm thinking that we could build the functionality into mozbot, and give a few of people the permission to trigger a deploy from Chat. What do you think?

**Comment by mmmavis** [comment]
@cadecairos does https://app.mozillafestival.org/ live on S3? 

> build the functionality into mozbot, and give a few of people the permission to trigger a deploy from Chat.

This sounds great to me, since data updates will be triggered by mozbot too. Can we also make pushing to `gh-pages` triggers updates to S3 production as well? 

Note that we should check with the program team to see if it's okay to update https://app.mozillafestival.org now with our WIP 2016 event app. Other than that, I think we should go ahead and have a staging instance set up first. 😉

**Comment by cadecairos** [comment]
> Can we also make pushing to gh-pages triggers updates to S3 production as well?

yeah we can set up travis to do this.

**Comment by mmmavis** [comment]
@cadecairos awesome! Do you want me to create a ticket on devops repo for setting up staging instance? 

I'll update you on next steps for production instance once I know more about the event app timeline. 🍻

**Comment by cadecairos** [comment]
yes please, lets ticket it up!

**Comment by mmmavis** [comment]
Production instance has been updated with 2016's app & schedule: https://app.mozillafestival.org/

There are some tasks in https://github.com/MozillaFoundation/mofo-devops/issues/415 that are left to do. I'll create another ticket to track them. 

Closing this ticket now. Good work team! 😉
