### ISSUE TITLE
Default landing page should be today's date (UX improvement)

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mozfest-event-app#250]
Default landing screen should change depending on the date:
- before the event: first day of the event (ex Friday for MozFest)
- first date of the event: first day of the event (ex Friday for MozFest)
- second day of the event: second day of the event (but first day is still available to click) (ex Saturday for MozFest)
- ...
- anytime after the event has ended: first day of the event (ex Friday for MozFest)

cc @mmmavis

**Comment by sarojpoudyal** [comment]
You mean currently on this date you want only friday to be shown and depending on the date of the event it has to change during the event?

**Comment by ryanpitts** [comment]
The UX behavior described in this ticket _should_ be the default behavior of the app. The `getChosenTab` method favors "today" if a user hasn't manually selected a tab already: https://github.com/mozilla/mozfest-event-app/blob/master/js/schedule.js#L431-L448

I think the problem might just be the way the dates are set in the config being passed from `index.html`: https://github.com/mozilla/mozfest-event-app/blob/master/index.html#L246-L250. The month in a Javascript dates is zero-indexed, so pretty sure that should just be a `9` not a `10`. (I have done this approximately 1 billion times myself in setting up the app for SRCCON :) )

**Comment by mmmavis** [comment]
@ryanpitts I need to verify if I accidentally broke that feature you originally built 😂 And about https://github.com/mozilla/mozfest-event-app/blob/master/index.html#L246-L250 ... I remember I did minus one from the index... apparently I was wrong again. Ha. Will update the code.
