### ISSUE TITLE
Remember scroll position when user clicks back button (UX improvement)

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mozfest-event-app#251]
If a user scroll to the bottom of the overview page, clicks on a card to see the detail view, then clicks the back button to go back to the overview page, they should be in the same scrolled down position as before the clicked on the detail view. 

cc @mmmavis

**Comment by kristinashu** [comment]
Should also remember which sections are open and which are collapsed (Default view should be collapsed view https://github.com/mozilla/schedule-app-core/issues/252)

**Comment by mmmavis** [comment]
Putting this in the current milestone.

I'm working on this but it will take some time to implement.

**Comment by alanmoo** [comment]
@mmmavis do you need some help with this one? I recall it being the number one thing that was frustrating about using the app last year.
