### ISSUE TITLE
Session meta to show on thumbnail view and detail view

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#258]
@kristinashu not sure if there's a ticket for this already. Feel free to close this one if it's a duplicate.

## thumbnail view
- title
- start time (& end time)
- Space
- location
- special label for "everyone" session

## detail view
- title
- date & start time (& end time)
- location
- Space
- Pathway
- facilitator(s): name? organization? twitter?
- special label for "everyone" session
- description
- link to etherpad / notes

thoughts? 🐹

**Comment by kristinashu** [comment]
Sounds good to me!

**Comment by mmmavis** [comment]
Hey @edrushka we're thinking to display session duration in the app. Do we have that meta already for each session?

**Comment by edrushka** [comment]
Good question! @Saallen do we have this info?

**Comment by Saallen** [comment]
Hi
We will mid Sept- facilitators may have picked a format that highlights a time frame but we should get the wranglers to confirm. Once curation is over they should know more.

On the thumbnail view I would want all the data I need to find the session
During the event I would want to know where this session will be so Space, floor, what room, time
![screen shot 2016-08-26 at 16 52 04](https://cloud.githubusercontent.com/assets/10194015/18011566/a36867a4-6bad-11e6-97e0-6b68e68cfa24.png)

**Comment by mmmavis** [comment]
updated the top comment to reflect @Saallen 's feedback 🌞

**Comment by mmmavis** [comment]
Closing. I believe this is done already. 😉

**Comment by mmmavis** [comment]
@kristinashu nice catch! Pathway info has been removed from the session cards.

**Comment by xmatthewx** [comment]
@kristinashu @Saallen @mmmavis – Are we sure that we don't want to include pathway info on the summary/thumbnail view? I think it can provide context when reading creative titles that might not be totally clear. Sorry that I'm late to the party.
