### ISSUE TITLE
How to indicate non-EN sessions

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozfest-event-app#260]
This year, we'll have a number of sessions (5-50 rough estimate) that will take place, wholly or partially, in languages other than English. 

What is the best way to indicate this in the schedule? We have a couple ideas but not sure if they make sense:
- non-English title?
- non-English description?
- dual language title and/or description?
- a tag of some kind?

And how should we indicate where each session fits on the spectrum (some sessions given entirely in another language with live translation, other sessions will be in EN and a second language, some sessions might just have non-EN support material)?

**Comment by kristinashu** [comment]
@edrushka any idea what the languages will be? @mmmavis has pointed out right to left languages will be tricky.

**Comment by edrushka** [comment]
Yes. We will be supporting 
- French
- German 
- Hindi
- Arabic
- Spanish 
- Italian

**Comment by edrushka** [comment]
Thanks for reminding me about the R-L issue. I realize this may limit our options.

**Comment by edrushka** [comment]
Also: one of us should do a session about supporting non-EN in festival infrastructure ;)

**Comment by mmmavis** [comment]
Doing a session about supporting non-EN at MozFest sounds great! It's too terrifying for me to host a session alone. I will see if I can find someone to co-host 👬 👭 👫  👬 👭 👫  👬 👭 👫

**Comment by kristinashu** [comment]
cc @xmatthewx

**Comment by ioana-chiorean** [comment]
Is it something I can help with @mmmavis ?

**Comment by xmatthewx** [comment]
This is all very exciting. 

I think we can find some not-too-hard ways to implement this. Here's one proposal to give us something specific to evaluate. 

 - English title (to avoid too much complexity)
 - Add a pathway tag for each language (for easy discovery via schedule list or pathway view)
 - Add a secondary description field
 - Add a field to identify secondary language (or direction)
 - Each description can mention level of language use

<img width="387" alt="screenshot 2016-09-06 17 23 54" src="https://cloud.githubusercontent.com/assets/53411/18291577/b6c51fc0-7456-11e6-8282-07f84956f5c0.png">

**Comment by edrushka** [comment]
This is great, @xmatthewx. Super helpful to have a starting point. 
**What I love:**
- English title (agree it's good to avoid complexity)
- Add a secondary description field (I assume this is the 'je suis la description' text in the example above. Will this work for Arabic, which is right-to-left?)
- Add a field to identify secondary language (can this be searchable somehow?)

**What I'm not sure about:**
- Each description can mention level of language use. (This might not be known until the actual session begins. If no French speakers attend the session, the facilitator will probably change the plan).
- Add a pathway tag for each language. (Is there another way to make it searchable or discoverable other than a pathway tag? Language doesn't quite fit with what we're trying to do with pathways).

**Comment by Saallen** [comment]
I love this mock up.
I would love to see the other language first, then underneath the English description. I would also see great value in the session name being visible in another language too
I do like the pathway as a way to capture the other but I might advice we come up with a strong name other than "other languages". I agree how we are design pathways do not fit with a language tagging system but I adding the complexity of tagging might be difficult

**Comment by xmatthewx** [comment]
I like your suggestion @Saallen that we have a nicely name pathway for all of these inclusive sessions, rather than a pathway for each language. Something like Translated web, Inclusive web, Localized web. 

I recommend that a non-EN session description include the translated title (instead of making a specific field). That will work well if we put that description before the English description.

**Comment by mmmavis** [comment]
hey @ioana-chiorean thanks for offering help 😉 🍰 I didn't end up proposing a session about supporting non-EN in festival infrastructure. But if you have any suggestion or feedback I'm interested in knowing more 😄

**Comment by kristinashu** [comment]
I don't actually think R-L will be an issue. It would just be the equivalent of us reading right aligned text (not ideal but doable for short amounts of text).

Here's an updated mockup:
- title in the other language (to make it obvious in thumbnail view)
- language icon with language
- English version of the title and description below, in the detail view
<img width="684" alt="screen shot 2016-09-19 at 3 54 00 pm" src="https://cloud.githubusercontent.com/assets/1068783/18651664/86408aee-7e81-11e6-8e17-ccc22a9a69af.png">

**Comment by edrushka** [comment]
Ohhh this is looking cool! Here are some real use-cases for sessions incorporating other languages:

[Programming a 2D Platform Game using Scratch] (https://github.com/MozillaFoundation/mozfest-program-2016/issues/144) – Session delivered in English. Mentoring, breakout groups and support materials in Spanish.
 
[Is InDesign a legit tool to form a design concept for website/webapp with appealing user interface?] (https://github.com/MozillaFoundation/mozfest-program-2016/issues/620) Session delivered entirely in German. Breakout, support and example websites also in German.
 
[Getting Started with Virtual Reality for the Web] (https://github.com/MozillaFoundation/mozfest-program-2016/issues/656). Session delivered in English with breakout groups in Spanish.

Note that 1 and 3 are delivered in English, while 2 is delivered in German.

**Comment by kristinashu** [comment]
Helpful to see some real examples. 

I'm assuming people will only attend a non-English session if they know that language, regardless of whether the session is partially or fully in that language. Also assuming everyone coming to MozFest speaks some English and could attend a session that is partially in English.

If that's true, then the exact break down isn't super important. We could add it to the description but I don't think it needs to be highlighted anymore than that.

**Comment by xmatthewx** [comment]
This all looks good design-wise. I leave it up to @mmmavis to guard us from too much extra implementation. 

I'm hesitant to promise using other languages in the primary title until she has a chance to dig into this. It adds another bit of logic that can break. It opens up more copy-paste errors that we might not notice. I'd rather have authors include the title at the beginning of their description so we only have a single field to manage (since there are just a few session like this). Again, I leave it to @mmmavis to decide what's easy and what's hard, but I recommend simplicity and caution.

I also think we should come up with a pathway to string together all these "localized" sessions.

**Comment by edrushka** [comment]
cc @hjbailey

**Comment by hjbailey** [comment]
@edrushka Very exciting well done!

**Comment by mmmavis** [comment]
I *think* we can just add 3 additional columns in the spreadsheet for wranglers to fill out the info

1. localized title
2. localized description
3. language name

This is my plan but I'll get back to you all tomorrow after I have time to test my assumption.

**Comment by kristinashu** [comment]
Thanks @mmmavis! I'll assign this ticket to you to test out hypothesis. Assign it back to me if you come across any problems and need design updates.

**Comment by mmmavis** [comment]
hey @edrushka 

How many non-EN languages can a session be conducted in? I was browsing https://github.com/MozillaFoundation/mozfest-program-2016 and found out some sessions have more than one non-EN language tags assigned.

**Comment by edrushka** [comment]
Some of the sessions may potentially have elements of more than 1 language in addition to English. This will likely be support materials or breakout groups (i.e. no one is suggesting they host a session in more than English plus 1 other language). I don't think we need translated text in the app description for the 3rd, 4th, 5th etc. languages - that's just going to be confusing. I propose we stick to highlighting the 1 main language people would like (in addition to English).

**Comment by mmmavis** [comment]
@edrushka 

> I propose we stick to highlighting the 1 main language people would like (in addition to English).

Cool, that would make things a lot easier on my end 🍻

**Comment by mmmavis** [comment]
Here we go 🎉  https://mozilla.github.io/mozfest-event-app/#_show-friday I've added 2 examples (one Arabic one French) to the Friday Science Fair block.

There will be 3 columns in the event app spreadsheet that need to be manually filled out for non-EN sessions

- `additional language` (e.g., Français)
- `localized title` (e.g., Bonjour le monde)
- `localized description` (e.g., bonjour la description du monde en anglais. bonjour la description du monde en anglais. bonjour la description du monde en anglais. bonjour la description du monde en anglais. bonjour la description du monde en anglais. bonjour la description du monde en anglais. bonjour la description du monde en anglais. bonjour la description du monde en anglais. )

**Comment by kristinashu** [comment]
Sweeeeet!

**Comment by edrushka** [comment]
Note: after email discussion we decided that we will only include a fully localized title and description for sessions that are entirely in another language. For sessions that are in both English and an additional language, we'll simply add a line that reads something like "Spanish speakers are welcome in this session". 

@mmmavis should that line go at the end of the English description, or in the Localized Description field?

**Comment by kristinashu** [comment]
@edrushka I don't really understand sessions that are partially in another language. If a session is partially in Spanish and I don't speak Spanish, can I still attend? 

"Spanish speakers are welcome in this session" sounds a little odd since Spanish speakers should be welcome at any session.

**Comment by edrushka** [comment]
@kristinashu it turns out that most session hosts are choosing to give their session principally in English, with support (e.g. breakout groups, mentorship, facilitated conversations, support materials, example websites) in additional languages. Anyone can attend any session at MozFest, but we need a way for Spanish speakers to know if they attend a particular session, they can interact with other Spanish speakers there. 

Originally we were going to translate the title and entire description into Spanish, but a) that is a lot of work and b) if the session is being largely delivered in English, that might give the wrong impression. This one-line is meant to be a solution to both those challenges.

Also, in case it wasn't clear above, "Spanish speakers are welcome in this session" would be written in Spanish.

**Comment by mmmavis** [comment]
@edrushka question: are there going to be any sessions that are conducted in a non-EN language **only**?

**Comment by edrushka** [comment]
At this moment there is not, but we haven't heard back from all space wranglers, so it's possible there may be some.

A session conducted in a non-EN language only would have a fully localized title and description.

**Comment by kristinashu** [comment]
Ok, that makes sense. I wonder if we should still highlight support languages in the thumbnail view though. Otherwise, it will be hard for people to discover.

**Comment by mmmavis** [comment]
Here's my proposal:

### For sessions that support a non-EN language OR sessions conducted in a non-EN language only

- highlight the language in thumbnail view. e.g, see "Spanish" in screencap below

<img width="759" alt="screen shot 2016-10-11 at 3 53 47 pm" src="https://cloud.githubusercontent.com/assets/2896608/19291585/f45652a2-8fca-11e6-8d00-31e05c92f13a.png">

### For sessions that support a non-EN language

- we don't do anything more

### For sessions conducted in a non-EN language only

- mention somewhere on the app that the session will be conducted in [language]
- we can keep the localized session title & description... or not? I think the `"session will be conducted in [language]"` note seems sufficient enough.

thoughts?

**Comment by hjbailey** [comment]
I thought the whole point of this exercise is one of language activism. When people see that we are able to support the festival in other languages it will encourage others to be brave and come forward. If we were going to run a festival in Japan - they would make sure everything was available in English so that Mozilla could attend. This is the one place we can open the doors in a very small way to say that language is important. We don't know what the knock on effect will be yet.

**Comment by edrushka** [comment]
I agree with Heather - we need to highlight these sessions in every way available to us. Here's how I would like to proceed.

### All multi-lingual sessions
- highlight the language in thumbnail view (see Mavis' screencap above)
- add to 'Multi-lingal MozFest' pathway

#### Sessions given in English with additional language support
- add a (translated) line to the English description (https://github.com/mozilla/mozfest-event-app/issues/398)

#### Sessions given entirely in another language (update: there are a few of these now)
- add a fully translated Title and Description

**Comment by edrushka** [comment]
Edited the comment above to provide clarity on the thumbnail view text

**Comment by mmmavis** [comment]
@edrushka 

for **"Sessions given entirely in another language"** do we still want the localized title and description to be the primary title/description (vs English ones)? See @kristinashu 's mockup in https://github.com/mozilla/mozfest-event-app/issues/260#issuecomment-248153155

**Comment by edrushka** [comment]
Yes, if it's given entirely in another language, let's make the localized title and description primary as in that example.

**Comment by mmmavis** [comment]
Cool, if that's the case there's nothing on my end needs to be done. Just make sure info is entered on the spreadsheet and things should show up correctly on the app.
