### ISSUE TITLE
MozFest timeblocks

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#307]
hey @edrushka @Saallen I remember someone mentioned to me this year sessions can only start at certain times. Is that true? If so could you list out all the timeblocks (or start times) below? Thanks!

**Comment by Saallen** [comment]
Sure

**Saturday**

- 9:00-9:30 main stage
- 10:00 -11:00 Session 1
- 11:15- 12:15 Session 2 (and D&D 1)
- 12:30 -13:30 Session 3
-     12:30- 14:00 Lunch
- 13:00 - 13:45 Sessions 4, (D&D 2 and Lunch cont).
- 14:00-15:00 Sessions 5
- 15:15- 16:15 Sessions 6 and D&D 3
- 16:30- 17:30 Sessions 7
- 18:00 Evening activities begin

**Sunday**

    

- 10:00- 10:45 main stage
-  11:00 - 12:00 Sessions 8 (and D&D 4)
- 12:15 - 13:15 Sessions 9
-     12:30- 14:00 Lunch
-     13:00- 13:45 Sessions 10, (D&D 5 and Lunch cont.)
-     14:00- 15:00 Sessions 11
-     15:15- 16:15 Sessions 12
-     16:30 - 17:30 Sessions 13
-     18:00 Demos

**Comment by mmmavis** [comment]
lovely! thanks @Saallen :) 

Just 2 questions - Anything on Friday? What does D&D mean?

**Comment by edrushka** [comment]
Friday is the Science Fair, which begins at 6:00.

D&D is Dialogues and Debates, which is the name of our Speaker series. The timing on those might change.

**Comment by xmatthewx** [comment]
Are you still discussing the timeblocks now? Or, do you just anticipate last minute changes regardless of what's decided now?

**Comment by Saallen** [comment]
Apart from D&D , everything else is confirmed start and end times

**Comment by xmatthewx** [comment]
Is there a chance that a D&D will fall outside the start times listed above? 

Can a session be longer than an hour and fill 2 or 3 time blocks? If so, we should expect sessions to only appear on the schedule in the first time block. We can specify its specific end time. Appearing in more than one time block would be difficult with a spreadsheet backend.

**Comment by edrushka** [comment]
1) D&D start times will not fall outside the established start times. They may be in different slots than the ones listed above, but they will begin at one of the official start times.

2) Yes, a session can be longer than 1 hour (note, they can be shorter than an hour, too. Some -- demos most likely -- may only be 15 minutes.) A session can go as long as the facilitator/space wrangler wants it to. Agree it would be better to specify length or end time. Adding it to multiple time blocks would be confusing.

**Comment by mmmavis** [comment]
@edrushka any idea how duration of each session is set? Is it assigned by Space wranglers or the session facilitators?

**Comment by edrushka** [comment]
Space wranglers will set the duration and allocate the start time (with input from the facilitators, of course).

**Comment by mmmavis** [comment]
Awesome! This means we can handle it directly on the event app spreadsheet. YEAH!

**Comment by mmmavis** [comment]
my question got answered. closing this ticket now. woohoooo
