### ISSUE TITLE
Determine which events to track with GA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mozfest-event-app#309]
Click on main menu items:
- [x] Logo and Schedule link
- [x] Spaces
- [x] Pathways
- [x] Search

Search:
- [x] if they enter a search term (is that possible?)

Date picker:
- [x] Fri, Sat, Sun (not sure this is useful?)
- [x] Favs

Session thumbnails:
- [x] Favorite it
- [x] click title to go to detail screen

Session detail view:
- [x] Favorite it
- [x] Notes button

Spaces:
- [x] click on each space to see detail view
- [x] session clicked on ~~in Spaces view~~
- [x] sessions favorited ~~in Spaces view~~

Pathways:
- [x] click on pathway title to see description
- [x] sessions clicked on ~~in Pathways view~~
- [x] sessions favorited ~~in Pathways view~~

**Comment by kristinashu** [comment]
@mmmavis I've listed a bunch of GA events. Let me know what you think.

**Comment by mmmavis** [comment]
Done! 

Note that due the current codebase setup we aren't able to track things to granular level. For example, we will know when users click on a session title to go to the detail view but we will NOT know which screen they are navigating from (e.g., individual space screens, day screens... etc)
