### ISSUE TITLE
Refine the header

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mozfest-event-app#316]
I think we should consider removing the logo from the header of this app. It's big and awkward and more site-like than app-like. 

A few thoughts:
 - We could add a simple splash screen with logo
 - Logo could remain on large wide desktop screens
 - We have a single small gear on left side of nav as a home button 
 - Might be a matter of taste, but the logo color on background color doesn't seem awesome

Regardless of what we decide, we need to optimize responsiveness. This is a screen shot of iphone 5 sized screen. 

<img width="329" alt="screenshot 2016-09-06 16 01 01" src="https://cloud.githubusercontent.com/assets/53411/18288939/4fffbd96-744b-11e6-980f-b4d4d698db08.png">

**Comment by kristinashu** [comment]
@xmatthewx would something like this be better? Just reducing the size of the logo and getting those menu items onto one line.
<img width="320" alt="screen shot 2016-09-20 at 12 22 39 pm" src="https://cloud.githubusercontent.com/assets/1068783/18685481/10d5e2e8-7f2d-11e6-899f-bbf5d00844a6.png">

**Comment by xmatthewx** [comment]
I just think the logo takes up too much valuable screen space on mobile. It's fine on desktop. Anyone looking at it on mobile knows what it's about. We could put the mozfest name below. Also, I still think that blue on purple color isn't really working. What about something like...

<img width="311" alt="screenshot 2016-09-20 16 26 11" src="https://cloud.githubusercontent.com/assets/53411/18687660/238f2774-7f4f-11e6-888e-e5216c062e13.png">

**Comment by kristinashu** [comment]
I understand removing a logo from a native app people use all the time (they click on the app icon on their phone and open the app everyday, year after years) but for a web app people only use 3 days once a year, I think we should include the logo. Also, since the logo goes away once the user scrolls down, it doesn't end up taking that much valuable realestate.

As for the color of the logo, this is a color combo Sabrina suggested and I quite like it. I get that there is some tension there but I think it's in a cool and funky way. The bright logo adds important branding and the app looks pretty plain (less fun) without it.

**Comment by xmatthewx** [comment]
We could keep the gear in the left corner of the nav. Either way...

 - It'd be great if the nav locked to a fixed position at the top when a user scrolls down below. It's a common pattern that'd help with the long, long lists. 
 - I guess I can get into the funky color combo, but it feels disconnected from the colors below. The pink, gray, and pastel purple look good, but seem like a different family. The electric blue or even the feeling just doesn't appear elsewhere. 
 - Can we post this to redpen for quick feedback from the team? I don't think this design went to crit at any point.

**Comment by kristinashu** [comment]
Ok, asked in channel https://redpen.io/p/ga54d8a78915b5a36a

**Comment by xmatthewx** [comment]
Okay thanks. I think that was helpful for other bits and pieces. We can run with header as is ... but let's be sure to test implementation on various screen sizes to make sure nav fits better than it does currently.

**Comment by kristinashu** [comment]
@mmmavis assigning to you to:
- reduce logo size
- reduce gaps between Schedule, Spaces, Pathways, Search icon (so that it fits on one line at narrow widths)
