### ISSUE TITLE
Display MozX (Art) pieces

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#321]
MozX (Art) pieces don't have start time therefore they won't show in the event app. Do we want to have MozX (Art) info on the event app? If so how should we display it?

/cc @kristinashu @xmatthewx

**Comment by mmmavis** [comment]
@edrushka @Saallen do we have a floor/section at Ravensbourne for the exhibition? Are all pieces/projects going to be presented at the same physical location?

**Comment by edrushka** [comment]
The MozEx exhibit will be spread throughout the building.

**Comment by xmatthewx** [comment]
I recommend we do a couple of entries (morning and lunch for visibility) that gives a brief overview and then links out to any digital resource made for the exhibition. We could ask the curator if they might want to highlight 1 item in each of the 4 time blocks.

**Comment by Saallen** [comment]
Lopping in @MozExhibit as they should decide

**Comment by Saallen** [comment]
Hey circling back on this as Dilemma of Connected spaces have also highlighted that they will have all day long events or experience in their space. 
It wont be an exclusively mozex issue.

**Comment by edrushka** [comment]
+1 to Matthew's suggestion of two schedule entries per day (one in the morning, one at lunch) with the descriptions mentioning it's an all-day exhibit/experience. Highlight different things in each of the 4 entries.

Does that work for your all-day entries in the schedule app, @MozExhibit @thornet?

**Comment by MozExhibit** [comment]
@edrushka @Saallen @xmatthewx @mmmavis @thornet - Hello! Yes, that is fine for us. And just so you know, we might have a digital trail/map that we can also link on those entries.

**Comment by mmmavis** [comment]
Hey @MozExhibit ,

Not sure if you are aware of this, but we have ported sessions info from the program repo to this [spreadsheet](https://docs.google.com/spreadsheets/d/1sG2nPX-vu4Dje6cJ-KlasRCgH_BgDm6q2iuBevYe3mg/edit#gid=1551861250). Let me know if you have trouble entering info/accessing the spreadsheet. 😉 Let's go with @xmatthewx suggestions: `"I recommend we do a couple of entries (morning and lunch for visibility)"`. Please feel free to reach out to me if you have any question! 😄

**Comment by Saallen** [comment]
hi @mmmavis I reached out to @MozExhibit and yes they agree to twice daily entries. How should this show up on the sheet? Can We add another row with this information on their tab
with decription, ID tag and time slot of 10am 14:00 etc??

Also they have a couple of sessions that are talks- do we delete all irrelevant rows except for this we want to show on the app??

**Comment by mmmavis** [comment]
@Saallen 

> Can We add another row with this information on their tab
with decription, ID tag and time slot of 10am 14:00 etc

Yup, just make sure each of the entries(rows) has an unique ID.


> Also they have a couple of sessions that are talks- do we delete all irrelevant rows except for this we want to show on the app??

The spreadsheet should only contain entries that we wanna show on the app. Otherwise please remove them from the spreadsheet (highlight the rows, right click, and select "clear row") 👍

**Comment by MozExhibit** [comment]
@mmmavis @Saallen @edrushka @xmatthewx - Hello! Sorry, I am getting a little confused here. In terms of the MozEx schedule and what info goes into the app, we only need the description of the MozEx space (as per here: https://mozillafestival.org/spaces-and-sessions) and that's it. We will add the MozEx digital book link to it - I aim to have that done by early next week. 

So, from the link you sent me for the app-info, I can see that there is list of the artworks, artists, and descriptions - but we don't need those for this. Just the overall description of MozEx, and then a link that we will pass you asap.

Does this help/clarify from our side?

**Comment by Saallen** [comment]
Hey @MozExhibit 
So partly right
We want to add the overall description
But if you have art works, or artist talks they must be presented on this spreadsheet too,
I would advise you go to the spreadsheet and delete the lines you don't want on the app-
Tidy up the descriptions of Art talk in walker space, or the artist in residence piece on level 7
@edrushka can help you with timings for talks in the walker space outside of D&D slots.
Happy to jump on a call if needed

**Comment by MozExhibit** [comment]
@Saallen @edrushka - Hi, I have tried to delete everything in the "grid-table", but it is not allowing me. We basically need to take everything out now, and only put one general MozEx descriptions. Can you try doing that please? Not sure why I cannot. 

Also - we don't need the Artist in Residence in here, and we will soon decide if we are going to have 2 talks in the walker-space or if perhaps we just don't have any.

**Comment by edrushka** [comment]
@mmmavis can you please help remove the entries on the MozEx tab?
