### ISSUE TITLE
Lock `mozfest-program-2016` repo

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#334]
https://github.com/MozillaFoundation/mozfest-program-2016 will be locked on Sept 27th. Session info will be ported to event app spreadsheet all at once and any changes made to that repo after Sept 27th will not reflect on the event app spreadsheet. Space wranglers will have to make changes directly to the spreadsheet.

**Comment by mmmavis** [comment]
I've ported everything from the program repo to the spreadsheet. I still need to massage the data a bit and will share spreadsheet out with MozFest program staff once it's ready.

@edrushka I didn't modify setting the program repo - people can still comment on tickets etc but it's just the changes won't be seen on the spreadsheet.

Gonna close this ticket now. Yeah!

**Comment by xmatthewx** [comment]
@edrushka – I recommend we change the settings in the repo in possible to avoid confusion later.

**Comment by edrushka** [comment]
How do we do that? What do you recommend?

**Comment by xmatthewx** [comment]
If wranglers have access to labels and milestones, I believe they could be demoted to just post comments. I can't tell because I actually don't have access to view [settings](https://github.com/MozillaFoundation/mozfest-program-2016/settings).

**Comment by mmmavis** [comment]
for backup purposes, here's the exported data in `.json` and `.csv` 

[exported-github-sessions.zip](https://github.com/mozilla/mozfest-event-app/files/499377/exported-github-sessions.zip)

**Comment by edrushka** [comment]
@xmatthewx I just gave you admin settings.
