### ISSUE TITLE
Port mozfest-program-2016 session data to spreadsheet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#335]
depended on https://github.com/mozilla/mozfest-event-app/issues/334

**Comment by mmmavis** [comment]
The following info will be ported from [` the "Session accepted" milestone`](https://github.com/MozillaFoundation/mozfest-program-2016/milestone/2) of the mozfest-program-2016 repo to the event app spreadsheet

- issue number
- issue title
- description (parsed from first comment of the issue)
- amended description (parsed from the "amended description" comment, if exist)
- name, twitter(if any), affiliated org (if any) info of the facilitator (parsed from first comment of the issue)
- space (parsed from `[Space _____]` label assigned to the issue)
- pathway (parsed from `[Pathway _____]` label assigned to the issue)

**Comment by mmmavis** [comment]
@edrushka do you think there's enough time to assign pathway labels to session tickets? If not wranglers can do it directly in the spreadsheet instead.

**Comment by edrushka** [comment]
@mmmavis I'm hoping to do that by EOD!

**Comment by mmmavis** [comment]
@edrushka awesome 🍰 🍸

**Comment by mmmavis** [comment]
Data has been ported to spreadsheet. I just need to massage the format a bit before I share it out.
