### ISSUE TITLE
Update D&D description and add D&D sessions to spreadsheet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#345]
Update Dialogue and Debate Speakers Series description when copy has been finalized: https://github.com/MozillaFoundation/Mozfest2016_production/issues/111

**Comment by edrushka** [comment]
Dialogues + Debates are MozFest’s speaker series -- 45-minute talks, with moderated Q&A sessions.

@KevZawacki is this ok for the schedule app description? It would go where the placeholder text is here: https://mozfest-app-2016.mofostaging.net/#_space-dialogue-and-debate-speakers-series

**Comment by KevZawacki** [comment]
@edrushka So people don't mistakenly think each speaker talks for 45 minutes apiece, can we tweak to either:

-- Dialogues + Debates is MozFest’s  TED-style speaker series

or

-- Dialogues + Debates are lightening talks and Q&As with big-name speakers
Thoughts?

**Comment by edrushka** [comment]
I prefer the 2nd. Can we call it an interactive lightening talk? As in:

-- Dialogues + Debates are interactive lightning talks with big-name speakers

**Comment by KevZawacki** [comment]
Perfect 👍

**Comment by edrushka** [comment]
@mmmavis final copy is 

Dialogues + Debates are interactive lightning talks with big-name speakers.

**Comment by mmmavis** [comment]
Lovely! I prefer the 2nd one too! 👍

**Comment by KevZawacki** [comment]
Pardon the re-open!

Wondering: In addition to the description we landed on, is it possible to speaker names in the scheduler app? So, one entry would look something like:

_**Saturday, 29 Oct., 11:15 - 12:15**: Dialogues + Debates are interactive lightning talks with big-name speakers. Zeynep Tufekci, Brian Behlendorf, Maggie Vail._

**Comment by edrushka** [comment]
@KevZawacki if I understand correctly, this text is the description for _all_ the D&Ds. The individual talks will be listed below, and would include the speakers names.

**Comment by mmmavis** [comment]
I'm not sure what the format is for D&D series - but I guess we can make the speakers "facilitators" so they appear as session meta and the session description can have detailed schedule, e.g., 10:15am - 10:30 Speaker A talks about web literary. 10:30am - 10:45 Speaker B talks about online privacy and security.

**Comment by KevZawacki** [comment]
@mmmavis That works for me! Let me know how I can help -- is there a document I can input / format that information in?

**Comment by mmmavis** [comment]
@edrushka mentioned she might be able to help - not sure if that statement is true still 😜

**Comment by edrushka** [comment]
I've inputted the first one on the spreadsheet. @mmmavis can you confirm I did this correctly (I confirmed the unique session IDs)

Can you please add Floor 0 - Walker Space to the list of locations?

**Comment by mmmavis** [comment]
Done! Just to note that I added protocol (https://) to the facebook link. This way it will show up as a hyperlink in schedule app.

**Comment by edrushka** [comment]
@KevZawacki Here's how it looks: https://mozfest-app-2016.mofostaging.net/#_session-913

What do you think?

**Comment by KevZawacki** [comment]
@edrushka Ah, this is great. Thanks! Couple small tweaks:

-- This one runs until 12:15, not 12
-- Next to the location pin, "Dialogue and Debate" should be plural

**Comment by edrushka** [comment]
@mmmavis can you please edit the D&D speaker series in the column F dropdown -- "Dialogue and Debate" should be plural.

**Comment by mmmavis** [comment]
DONE! https://mozfest-app-2016.mofostaging.net/#_space-dialogues-and-debates-speakers-series

thanks team! 🍻

**Comment by edrushka** [comment]
Not so fast, @mmmavis! Put those beers back in the fridge because this is not done 😆 

@KevZawacki if you're happy with this format, can you please enter the rest of the D&Ds into the spreadsheet. I just did the first one to get it right.

Spreadsheet is here (you have edit access): https://docs.google.com/spreadsheets/d/1sG2nPX-vu4Dje6cJ-KlasRCgH_BgDm6q2iuBevYe3mg/edit?ts=57ec5613#gid=305672037

**Comment by KevZawacki** [comment]
Certainly -- spreadsheet has been updated.

**Comment by mmmavis** [comment]
Looking awesome: https://mozfest-app-2016.mofostaging.net/#_space-dialogues-and-debates-speakers-series ✨
