### ISSUE TITLE
Add Space icons 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#346]
Add Spaces icons when they are ready. They should show up on Spaces overview page and individual Space page.

See design: https://projects.invisionapp.com/share/ZU8H4AZS3#/screens/185660147

**Comment by kristinashu** [comment]
I'll assign this one to myself to export the icons once they are ready. Will assign back to @mmmavis once they're ready!

**Comment by kristinashu** [comment]
W00t got the icons!  https://drive.google.com/drive/u/1/folders/0B2irLVDJivhLaEZ2RTk1Q0JWZE0 I just need to color them and determine dimensions.

**Comment by kristinashu** [comment]
@mmmavis here are the icons:
[Space icons.zip](https://github.com/mozilla/mozfest-event-app/files/499255/Space.icons.zip)

**Comment by kristinashu** [comment]
Here are the widths for each icon:
open science: 39px
localisation: 24px
youth zone: 37px
journalism: 29px
open badges: 33px
Digital Arts and Culture: 37px
Fuel The Movement: 40px
Demystify the Web: 27px
Dilemmas in Connected Spaces: 33px
MozEx: 37px
