### ISSUE TITLE
Add notice that we use cookies 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/mozfest-event-app#347]
There should be a notice that we will be using cookies to track their favorite sessions
cc @mmmavis

**Comment by ryanpitts** [comment]
unless something's changed, the app doesn't use cookies (it uses the `localStorage` API)

**Comment by mmmavis** [comment]
That is correct @ryanpitts :smile: we use `localStorage` but not cookies . Thanks for filing this ticket @ioana-chiorean !
