### ISSUE TITLE
List view for pathways and spaces

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mozfest-event-app#363]
Feedback from the design team was that the Pathway and Space list view is too clunky. Please remove the white box background to tighten up the list.
https://redpen.io/cod78aa956306daff3

<img width="282" alt="screen shot 2016-09-22 at 12 47 31 pm" src="https://cloud.githubusercontent.com/assets/1068783/18763561/c9dfabb6-80c2-11e6-97a3-05aedb80192e.png">
<img width="319" alt="screen shot 2016-09-22 at 12 47 41 pm" src="https://cloud.githubusercontent.com/assets/1068783/18763562/c9dfdec4-80c2-11e6-9c25-dd3ce4bbdd3e.png">

**Comment by mmmavis** [comment]
@kristinashu hover state styling stays the same?

**Comment by kristinashu** [comment]
What does it do now, add an underline on hover? If so, that works for me.

**Comment by mmmavis** [comment]
Removing white background from the list item makes those arrows look out of place on larger devices. I talked to @kristinashu on this and we decided to move the arrow closer to the text. 

<img width="317" alt="screen shot 2016-09-30 at 4 19 26 pm" src="https://cloud.githubusercontent.com/assets/2896608/19017319/38540708-87ea-11e6-8770-06a777e09e74.png">

**Comment by kristinashu** [comment]
Icons look sweet!
