### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mozfest-event-app#364]
Few small design things:
- [ ] reduce height of the date picker
- [ ] Session time text should be grey not blue
- [x] line should be lighter grey
- [x] arrow icon should be lighter blue and much smaller
- [ ] icons in session cards should be smaller (and maybe lighter)

(Note: card widths are different but I think it's good the way it is on staging so ignore that the comp card goes all the way to the edge of the screen)

Staging on the left and redpen on the right:
<img width="727" alt="screen shot 2016-09-22 at 11 52 28 am" src="https://cloud.githubusercontent.com/assets/1068783/18765533/f8d074fc-80ca-11e6-9781-d813d00c4f05.png">

**Comment by mmmavis** [comment]
Done! https://mozfest-app-2016.mofostaging.net/

**Comment by kristinashu** [comment]
Looks great!
