### ISSUE TITLE
Remove "back" from Spaces and Pathways pages

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#366]
There are 3 ways for a user to get to individual space/pathway page:

1. via direct link. e.g. https://mozilla.github.io/mozfest-event-app/#_space-journalism
2. by clicking the Space meta in a session's detail view. e.g., https://mozilla.github.io/mozfest-event-app/#_session-301
3. clicking a particular space/pathway item from the space/pathway overview page: https://mozilla.github.io/mozfest-event-app/#_spaces

Right now doesn't matter which route you took the "Back" link on  individual space/pathway page always take you back to the overview page, which can be very confusing. Since we can't easily track which route a user took, I'd like to suggest that we remove the "Back" button.

/cc @kristinashu

**Comment by kristinashu** [comment]
Sure, go ahead and remove it. As long as 'back' button still shows up on a [session detail screen](https://mozilla.github.io/mozfest-event-app/#_session-101) (where this 'back' button seems to work well).

**Comment by mmmavis** [comment]
Though not the best way to implement this but it was the easiest - the Back button on detail view simply triggers history's back() method (the same as triggering browser's back button). And yea, we can keep this one.
