### ISSUE TITLE
Timeblock labels

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#369]
Here are the labels I have for the timeblocks:

Science Fair
Main Stage
Session 1
Session 2 (and D&D 1)
Session 3
Lunch
Sessions 4 (and D&D 2)
Session 5
Session 6 (and D&D 3)
Session 7
Evening Activities
Main Stage
Session 8 (and D&D 4)
Session 9
Lunch
Session 10 (and D&D 5)
Session 11
Session 12
Session 13
Demos

------

they will appear as "dividers" in the app 

<img width="756" alt="screen shot 2016-09-27 at 4 52 34 pm" src="https://cloud.githubusercontent.com/assets/2896608/18895993/d70b32e2-84d2-11e6-84d0-2dd94b6ece9a.png">

are we good with these labels? do we want to update the wording? 

/cc @edrushka @kristinashu

**Comment by edrushka** [comment]
@Saallen Are we calling Sunday evening "Demos" or "Demo Party"?

**Comment by kristinashu** [comment]
We could instead show start times. So "Session 2" would say "Sat 1PM"? Like last year: https://app.mozillafestival.org/#_show-saturday

**Comment by edrushka** [comment]
Oh yes, that's much more helpful. Numbering the session slots and speaker slots was really to help Space Wranglers (and Kevin!) with their programming. The actual times are much more valuable to attendees.

**Comment by mmmavis** [comment]
+1

**Comment by mmmavis** [comment]
**Updated timeblock labels:**

Friday Science Fair
Saturday Main Stage
Saturday 10AM
Saturday 11:15AM
Saturday 12:30PM
Saturday Lunch
Saturday 1PM
Saturday 2PM
Saturday 3:15PM
Saturday 4:30PM
Saturday Evening Activities
Sunday Main Stage
Sunday 11AM
Sunday 12:15PM
Sunday Lunch
Sunday 1PM
Sunday 2PM
Sunday 3:15PM
Sunday 4:30PM
Sunday Demos

**Comment by Saallen** [comment]
Hey- Closing demo party or demo party 
Can we add the lunch time to be 12:00- 14:00?
So people dont think it is just 12:00 and dont go to lunch time sessions

**Comment by xmatthewx** [comment]
When I'm viewing the Sunday schedule, I don't need to see the word Sunday on each timeblock. Redundant and it makes sched harder to scan. In other views (favs, pathways, etc) the day is useful info. 

@mmmavis, if others agree, can you think of a not-too-tricky logic to achieve that?

**Comment by kristinashu** [comment]
Yes, would be great if there was an easy way to do this! 

Otherwise, we could shorten "Saturday" to "Sat" but not showing the day on the schedule screens would be ideal.

**Comment by kristinashu** [comment]
Yes, would be great if there was an easy way to do this! 

Otherwise, we could shorten "Saturday" to "Sat" but not showing the day on the schedule screens would be ideal.

**Comment by KevZawacki** [comment]
@edrushka 

1) No need to number them
2) Let's call them "Keynote Speaker Series" in the schedule app

**Comment by mmmavis** [comment]
I'll shorten the day to 3-letter, e.g., Saturday to Sat etc. Conditionally show/hide the day label might be tricky and will introduce complexity to the codebase - I'll see what I can do.

**Comment by xmatthewx** [comment]
> will introduce complexity to the codebase

Definitely don't stretch yourself to do this unless there's an easy solution. Maybe wrap day name in a tag and hide with CSS?

Thanks @kristinashu and @mmmavis for making something so great that we can even consider little details like this.

**Comment by kristinashu** [comment]
Based on our convo in chat: 
If we incooperate "Keynote Speaker Series" in the timeblock label (example: Sat 11:15AM (Keynote Speaker Series)) it will look like that timeblock is only for Keynote Speaker Series. We decide not to include it in the time block label, but it will still appear as "Keynote Speaker Series" in the session card for each keynote event.

**Comment by mmmavis** [comment]
@xmatthewx thanks for the suggestion! 😄 the names come from the "timeblock name" column in the spreadsheet which I can't anticipate what values they are going to be (e.g., a new timeblock could be added during MozFest etc). Also I try to avoid adding more jQuery hide/show logic as we are already doing a ton in the codebase. jQuery is good for UI manipulation but using it to build an app is not ideal. Since we don't have the time luxury to rewrite it and there's no test we can run, I'm trying my best to not add more complexity to it so we don't accidentally break something. 😉  

<img width="780" alt="screen shot 2016-09-28 at 12 48 39 pm" src="https://cloud.githubusercontent.com/assets/2896608/18929581/ee3946be-8579-11e6-8c07-eeb92ed183ea.png">

**Comment by mmmavis** [comment]
### Final timeblocks

---

Fri Science Fair

Sat Main Stage
Sat 10AM
Sat 11:15AM
Sat 12:30PM
Sat Lunch
Sat 1PM
Sat 2PM
Sat 3:15PM
Sat 4:30PM
Sat Evening Activities

Sun Main Stage
Sun 11AM
Sun 12:15PM
Sun Lunch
Sun 1PM
Sun 2PM
Sun 3:15PM
Sun 4:30PM
Sun Demos

**Comment by xmatthewx** [comment]
I forgot that those strings were merged in the spreadsheet, not when you generated your json. So we can't add markup. This would be easy peasy with a real database. Oh well.
