### ISSUE TITLE
Update Pathways' name & short description

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#370]
@edrushka 

Can you help provide a one-line description for each of the pathway below? Thanks!

<img width="289" alt="screen shot 2016-09-27 at 6 49 04 pm" src="https://cloud.githubusercontent.com/assets/2896608/18897934/2607ddfe-84e3-11e6-9e0f-44c54b055a30.png">

**Comment by edrushka** [comment]
#### Storytelling

There are countless ways to tell a story, but how can you use web-native media to tell your story in new ways? Learn and share techniques for amplifying your voice and message on the web.

#### The future of the web
Debate the ethics and philosophy of technology, and what it means to be a citizen on the web, by exploring how much control we have over our data and how we can use it for the greater good.

#### AR, VR and Machine Learning

Who does technology belong to? Where are the boundaries between understood reality and algorithms? Explore the possibilities of machine learning, augmented reality and virtual reality.

#### Digital Inclusion
Investigate the issues and blockers that young people, people with mixed abilities, people from different cultures and people who speak different languages face on today's web.

#### Concrete Digital Skills
Sharpen your digital and web literacy skills so you can teach and credential other people who want to know how to live, learn, and work on the web.


#### Localized MozFest
Join a multi-lingual session and learn how language impacts our experiences on the web.

----
@Saallen please review - I had to shorten our paragraph-length descriptions.

**Comment by Saallen** [comment]
Hey
amended one title- concrete skills to Web literacy and grassroots advocacy

I think you should expand a little more on Localised MozFest- I am not sure this description matches your pathway- "Learn how language impacts our  impacts our experiences on the web....." is not really the outcome here as there is no post discussion here, its a self discovery of this impact...

**Comment by Saallen** [comment]
@edrushka Do you have a short description for this page yet?

**Comment by edrushka** [comment]
@Saallen 
1) Do you mean the page for the Festival Guide? If so, yes, it's here: [Multi-Lingual MozFest] (https://github.com/MozillaFoundation/Mozfest2016_production/issues/113). Perhaps we should update the pathway name to match this title.
2) I think 'Web literacy and grassroots advocacy' might be too long for the schedule app. @mmmavis can you let me know if that's too many characters? We could shorten it to "Advocacy & Web Literacy'

I'll revise the localization description when I have a minute, hopefully by EOD tomorrow.

**Comment by Saallen** [comment]
Hey @edrushka I meant the page on the schedule app- how are you introducing the pathways as a collective?

**Comment by mmmavis** [comment]
> how are you introducing the pathways as a collective?

@Saallen something like this: https://mozfest-app-2016.mofostaging.net/#_pathways 😄 

> I think 'Web literacy and grassroots advocacy' might be too long for the schedule app. @mmmavis can you let me know if that's too many characters? We could shorten it to "Advocacy & Web Literacy'

@edrushka schedule app doesn't care how long a pathway name is. It's just this work as a pipeline. If we want to make a change I'll have to update existing pathway name in spreadsheet and/or update the script, plus update schedule app so pathways show up correctly. In other words, the earlier we can lock pathway names the better. 😉

**Comment by mmmavis** [comment]
<img src="https://cloud.githubusercontent.com/assets/2896608/18974731/eb0872cc-8659-11e6-9efb-b35e917c40d1.png" width="320">

@edrushka @kristinashu it looks nicer on small device if it's "Advocacy & Web Literacy"

**Comment by edrushka** [comment]
I agree, it looks much nicer when it's "Advocacy & Web Literacy". If all the rest fit on one line on smaller devices, I'm inclined to keep that one short for consistency. 

As for the description that's currently placeholder text, I'm going with something really short so it doesn't push the actual pathways down on the screen:

Pathways are a set of sessions curated by interest, topic or technology that will help you explore a variety of Spaces.

**Comment by edrushka** [comment]
@mmmavis would you be so kind as to share a screenshot of what the pathways page looks like with all the real names and that description?

**Comment by mmmavis** [comment]
@edrushka, based on 320px wide screen

<img src="https://cloud.githubusercontent.com/assets/2896608/19005153/d8e2c2fa-870d-11e6-8fe0-f9f09793fa9b.png" width="320">

<img src="https://cloud.githubusercontent.com/assets/2896608/19005014/56353c5c-870d-11e6-95ba-c2fee63fb04c.png" width="320">

**Comment by mmmavis** [comment]
for consistency, should we turn `The future of the web` into `The Future of the Web`

**Comment by edrushka** [comment]
Nice - I feel like the length of the overall pathways explanation and the individual descriptions is about right. 

Agree we should turn The future of the web into The Future of the Web

Also for consistency, lets turn AR, VR, and Machine learning into AR, VR & Machine Learning.

I still owe you a better pathway description for Localized Mozfest so don't close this ticket yet.

**Comment by kristinashu** [comment]
And if we use some version of "Localized" it should be "Localised" (to be _localised_ for the UK!).

**Comment by edrushka** [comment]
I actually propose we change the title of that pathway to Multi-Lingual MozFest

Multi-lingual MozFest
These multi-lingual sessions will help you connect with a global community working to make the web a more inclusive space for the millions of users who do not speak English.

**Comment by mmmavis** [comment]
I've pushed our WIP pathway names and descriptions onto staging: https://mozfest-app-2016.mofostaging.net/#_pathways Let me know when things are finalized and I'll update the list again 😉 . Note that pathway name will be included as part of the URL (e.g., https://mozfest-app-2016.mofostaging.net/#_pathway-ar-vr-machine-learning ) So it'd be the best if we don't change them after I make the final edits live 😂

**Comment by edrushka** [comment]
@Saallen are we good with these final pathway names? We can't change them, so need to sign off now: https://mozfest-app-2016.mofostaging.net/#_pathways

**Comment by Saallen** [comment]
Looks good

**Comment by mmmavis** [comment]
Final pathway names:

- `AR/VR/Machines` --> `AR, VR and Machine Learning`
- `Concrete Skills` --> `Advocacy & Web Literacy`
- `Digital Inclusion` --> `Digital Inclusion`
- `Future of the Web` --> `The Future of the Web`
- `Localized MozFest` --> `Multi-lingual MozFest`
- `Storytelling` --> (same) `Storytelling`

I'll make the change in spreadsheet, script, and schedule app soon! 🍷
