### ISSUE TITLE
Update production app with some "coming soon" message

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#378]
The production site https://app.mozillafestival.org/ currently still shows last year's app. Let's update it with some sort of "2016 schedule coming soon" message. I think something really simple will do since we will update the production site with the real 2016 app in 2 weeks.

/cc @kristinashu @edrushka

**Comment by kristinashu** [comment]
Good call @mmmavis. Not super exciting but how about something like this:

<img width="318" alt="screen shot 2016-10-03 at 10 58 37 am" src="https://cloud.githubusercontent.com/assets/1068783/19047834/612c38b6-8958-11e6-9ea8-7e8851dfa619.png">

**Comment by edrushka** [comment]
Works for me! Let's keep it simple :)

**Comment by mmmavis** [comment]
Notes for myself: follow instructions in https://github.com/MozillaFoundation/mofo-devops/issues/415#issuecomment-251137403 to have https://app.mozillafestival.org/ updated.

**Comment by mmmavis** [comment]
Here we go: https://app.mozillafestival.org/ 🍸 🏖
