### ISSUE TITLE
Add list of locations to spreadsheet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#379]
@edrushka I can help add the locations/rooms to the spreadsheet. Just let me know when the list is finalized! 😉

**Comment by edrushka** [comment]
Do you mean room numbers?

**Comment by mmmavis** [comment]
@edrushka yup yup

**Comment by edrushka** [comment]
ping @Saallen to paste rooms here when they are known

**Comment by Saallen** [comment]
Program rooms 
Level 0
* Foyer
* Walker space

Level 1
* Green Room
* Mezzanine room
* Post graduate area

Level 2
*205
*206
*207
*208
*209/210
* 211
* 212
*213

Level 3
* 301/Open media

Level 4
* Library
* Big space

Level 5
* 

Level 6 
* 601
* 602
* 603
* 604
* 605
* 606
* 607

Level 7
* 702
* 703
* 706
* 707

Level 8 
* 801
* Boardroom
* Executive suite
* 804
* 805
* 806



Level 9
* 902
* 903
* 906
* 907
* 908

**Comment by Saallen** [comment]
@edrushka and @mmmavis 
This list is needs further additions if being used for floor plans

**Comment by mmmavis** [comment]
List of locations/rooms have been added to the spreadsheet ✨ See below:

Floor 0 - Foyer
Floor 0 - Walker Space

Floor 1 - Green Room
Floor 1 - Mezzanine Room
Floor 1 - Post Graduate Area

Floor 2 - 205
Floor 2 - 206
Floor 2 - 202
Floor 2 - 207
Floor 2 - 208
Floor 2 - 209/210
Floor 2 - 211
Floor 2 - 212
Floor 2 - 213

Floor 3 - 301/Open media

Floor 4 - Library
Floor 4 - Big Space

Floor 6 - 601
Floor 6 - 602
Floor 6 - 603
Floor 6 - 604
Floor 6 - 605
Floor 6 - 606
Floor 6 - 607

Floor 7 - 702
Floor 7 - 703
Floor 7 - 706
Floor 7 - 707

Floor 8 - 801
Floor 8 - Boardroom
Floor 8 - Executive Suite
Floor 8 - 804
Floor 8 - 805
Floor 8 - 806

Floor 9 - 902
Floor 9 - 903
Floor 9 - 906
Floor 9 - 907
Floor 9 - 908

---


@Saallen few questions for you:

- 209/210 <--- is this one room or 2 rooms?
- 301/Open media <-- same q, is this one room or 2 rooms?
- No rooms on Floor 5?

**Comment by Saallen** [comment]
Yo-
209 and 210 are separate rooms but we make it into one- so you can drop one number
310/open media is the same room but decide which title is better for the schedule
No programmable space on level 5 but there is location here for floor maps

**Comment by mmmavis** [comment]
Thanks @Saallen 😉 
I'll drop 210 and Open Media.

**Comment by mmmavis** [comment]
DONE! ✨ 🎆

**Comment by Saallen** [comment]
🍾
