### ISSUE TITLE
Update Sunday first block

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozfest-event-app#392]
First timeblock on Sunday should change to:
09:30
Networking Breakfast
(there is no mainstage so you can delete the 10:00 timeblock)

**Comment by mmmavis** [comment]
@edrushka 

I'm about to make this change in the spreadsheet. Do we want to call the 9:30 block as "Networking Breakfast" still? Or just "Breakfast"?

**Comment by edrushka** [comment]
MozFest Breakfast.

Sorry - I thought I changed that in the programmatic tab on the spreadsheet.

**Comment by mmmavis** [comment]
No worries. It has to be changed in the Timeblock tab first and then in the programmatic tab, you select the updated value from the timeblock dropdown (dropdown values come from the Timeblock tab). This way we can prevent wranglers from adding their own timeblocks to the schedule 😉

**Comment by edrushka** [comment]
Good call. I was thinking of adding a couple 'Nap' timeblocks.
