### ISSUE TITLE
Amendments to programic timings

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-event-app#397]
Hello @mmmavis  and @edrushka - small edits requests to program timings on the  schedule spreadsheet

Can you 
*update the lunch start time on Saturday to 12:00pm?
* MozFest Networking breakfast to MozFest Breakfast	

Can I add descriptions please to some these elements? I think SF, DEMO and Breakfast need more descriptions?

**Comment by edrushka** [comment]
Wait - @Saallen the reason I put that is that some people think "MozFest Breakfast" is for a special group. I've been hearing "am I invited to this?" - I thought that by adding networking it might indicate it's for everyone.

**Comment by edrushka** [comment]
I made this change (we went with MozFest Breakfast).

**Comment by mmmavis** [comment]
I've updated the lunch start time on Saturday to 12:00pm. 😉
