### ISSUE TITLE
Clean up slider animation code

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#426]
We should probably be able to just rely on jQuery's `slideDown()` and `slideUp()` instead of writing our own logic and animation.

Also the blocks should start off hidden. Currently a block is first 100% visible and it quickly slides up to make itself hidden - we should fix this.

**Comment by ryanpitts** [comment]
fwiw, I had originally been using slideUp() and slideDown() for that feature, but was seeing some weird performance issues. IIRC it was stuttering a bit, but the bigger problem was cutting off the bottom of the div when you'd close and reopen, or when content inside the div changed.

So I switched it to animate height instead, using this technique: https://davidwalsh.name/css-slide. (Also totally agree that starting the blocks off hidden is better, but the only way I could store the full height for animation purposes was to render then hide :| ) I really should have documented why I did the animations this way, ugh sorry I didn't.

But if this is working great, then awesome! I just wanted to leave this here for reference in case you spot anything weird with divs not sliding properly.

**Comment by mmmavis** [comment]
Thanks so much for providing context @ryanpitts . Very useful info!

I have not yet discovered any cutoff issue (maybe jQuery has fixed the issue?) but if it comes back again thanks to your input I will know what causes the problem and I will revert the code back to the custom animation you put together. 🍻
