### ISSUE TITLE
Format sessions as microformats

### ISSUE THREAD

**Issue by SpikeUK** [mozilla/mozfest-event-app#430]
Is it possible/desirable to format sessions as microformat events?

If formatted as an h-Event (http://microformats.org/wiki/h-event) users could add the sessions they wish to attend to their calendar applications.

Are microformats still used @mmmavis ?

**Comment by mmmavis** [comment]
Hey @SpikeUK , wow I'm not aware of the existence of h-Event. Thanks for sharing! 🍸 🍸  I'll dig into it sometime next week after I complete other pressing tasks first. Do you have a link to any site or app that's using h-Event? I would love to check it out.

**Comment by SpikeUK** [comment]
Looks like Microformats are not all that popular these days - they seem to have lost the traction that they gained when I was a website developer allllllllll those years ago.

**Comment by mmmavis** [comment]
Hey @SpikeUK , without this ticket I wouldn't have known the existence of h-Event. Thanks for broadening my knowledge 😉

**Comment by SpikeUK** [comment]
You are most welcome @mmmavis ! It seems that Microformats have not lived-up to their early potential and they are not as used as widely as I had imagined. Back in the day Tantek Çelik (https://mozillians.org/en-GB/u/mozt/) was a great evangelist and it would not hurt to reach out to him :)
