### ISSUE TITLE
App appears to be missing content when first visiting

### ISSUE THREAD

**Issue by alanmoo** [mozilla/mozfest-event-app#432]
It took me a minute to realize that the horizontal dividers were clickable. I get not wanting to overwhelm users with all of the content at once, but maybe the first section of each list could open by default so people might have a better chance of realizing there's content inside it?

**Comment by alanmoo** [comment]
@mmmavis @xmatthewx

**Comment by kristinashu** [comment]
Yes, I like that idea. @mmmavis how much work would it be to do this?

**Comment by mmmavis** [comment]
@kristinashu it shouldn't require too much work. I'll mark this as "enhancement" though as I need to get other urgent things done first.

Thanks you @alanmoo for the suggestion.

**Comment by alanmoo** [comment]
Would this be something that a contributor might be able to do? Maybe a label indicating as much would be useful?

**Comment by xmatthewx** [comment]
Good suggestion @alanmoo. The Friday view especially suffers from this. Toggling that one open would be an improvement for sure. On the other views, it might be annoying later on if the app doesn't remember that you closed the first section.

**Comment by mmmavis** [comment]
Done. https://mozfest-app-2016.mofostaging.net/

**Comment by xmatthewx** [comment]
Looks good overall. One problem: the arrow should be toggled too.
