### ISSUE TITLE
Replace 'post graduate area' with 101 & 102

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozfest-event-app#438]
In column E (location) on the Spreadsheet, replace "Floor 1 - Post Graduate Area" with "Floor 1 - 101" and "Floor 1 - 102"

**Comment by mmmavis** [comment]
@edrushka do we want to reassign a room for https://mozfest-app-2016.mofostaging.net/#_session-349 since it's currently using "Floor 1 - Post Graduate Area"?

**Comment by edrushka** [comment]
Yes, we'll reach out and let the Badges peeps reassign. I guess put 101 for now, so it shows up in the schedule.

**Comment by mmmavis** [comment]
Adjustment has been made in the spreadsheet! 😉
