### ISSUE TITLE
Export icon files so they are on white

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#443]
@kristinashu could you export [these apple icon files](https://github.com/mozilla/mozfest-event-app/tree/master/img/favicon) again so they are on white background? Thanks!

**Comment by mmmavis** [comment]
@kristinashu I can take this on if you are too busy. I just learnt how to do it in Illustrator lol. The PNGs were on a weird big white artboard when I viewed them on Illustrator but I just learnt I can simply delete that background artboard before I "save for Web" 😂

**Comment by kristinashu** [comment]
@mmmavis if you can, that would be great! Thanks!

**Comment by mmmavis** [comment]
yup, im on it!
