### ISSUE TITLE
Autogenerate session notes URLs in the spreadsheet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#451]
Spreadsheet related.

For sessions that aren't already using the  `notes url` field we should autogenerate an Etherpad link for them.

**Comment by mmmavis** [comment]
so the notes URL will be generated based on the session title:`https://public.etherpad-mozilla.org/p/mozfest-2016-[title]`. e.g., https://public.etherpad-mozilla.org/p/mozfest-2016-the-newsroom

/cc @edrushka @xmatthewx

**Comment by edrushka** [comment]
works for me! some of the titles are crazy long, though. Should we limit it to a few words, or does that make things more complicated?

**Comment by mmmavis** [comment]
@edrushka yea unfortunately that would make things a lot more complicated since we have to do this in spreadsheet 😅 If people are not happy about the autogenerated URL we can always overwrite it manually.

**Comment by edrushka** [comment]
OK lets go with simple! Thanks for explaining.

**Comment by mmmavis** [comment]
Done!
