### ISSUE TITLE
Etherpad error - Such a padname is forbidden

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozfest-event-app#460]
This session: https://app.mozillafestival.org/#_session-283
gives the etherpad error "Such a padname is forbidden" [Screenshot] (https://www.dropbox.com/s/jnskxc6cfi763t5/Screenshot%202016-10-20%2011.39.57.png?dl=0)

I wonder if it's because of the hyphen in the session title?

cc @xmatthewx @mmmavis

**Comment by mmmavis** [comment]
there seems to be some restrictions on Etherpad slugs

- needs to be shorter than 51 characters
- not ends with hyphen(-)
- (...and more...... I'll find out)

**Comment by xmatthewx** [comment]
I'm okay with truncating the name for the URL. If you don't know after 50 characters what the pad is for, I doubt more words will help. 😈

**Comment by edrushka** [comment]
WFM if that's simple to implement! Did we determine if it's the length that broke the pad for this particular session, or was it the hyphen in the title?

**Comment by mmmavis** [comment]
@xmatthewx we did the same for London - we just didn't have long session names I guess.

@edrushka either can cause problem.

**Comment by mmmavis** [comment]
Here's the Google function we can use 👀 ...

This will grab the first 37 character from session title (50 - length of `mozfest-2016-`) 
--> replace non alphabetic character with `-` (dash)
--> strip trailing invalid characters (e.g., dashes)
--> turn everything lowercase

@edrushka @xmatthewx let me know if ^ this plan look good to you.

```
=if(
  A3="","",
  CONCAT(
    "https://public.etherpad-mozilla.org/p/mozfest-2016-",
    LOWER(
      REGEXREPLACE(
        REGEXREPLACE( 
          REGEXREPLACE(
            LEFT(A3,37),
            "[^a-zA-Z]",
            "-"),
          "[\s]",
          "-"
        ),
        "[^a-zA-Z]+$",
        ""
      )
    )
  )
)
```

**Comment by xmatthewx** [comment]
I ❤️ regex. :eye: looks good.

**Comment by mmmavis** [comment]
kk I'll apply this change to spreadsheet now!

**Comment by mmmavis** [comment]
nvm I'm heading to my dentist appointment soon. Will tackle this after since it might take some time to do.

**Comment by mmmavis** [comment]
Done! 🎉

**Comment by edrushka** [comment]
Yay it works now!!  https://public.etherpad-mozilla.org/p/mozfest-2016-science-support---how-to-get-outside

Thanks Mavis 🌷 🌻 🌹
