### ISSUE TITLE
Default to Spaces

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozfest-event-app#461]
Make https://app.mozillafestival.org default to the /#_spaces content rather than the schedule 

cc @xmatthewx

**Comment by mmmavis** [comment]
Do we want https://app.mozillafestival.org to show what's current on https://app.mozillafestival.org/#_spaces ? Or do we want https://app.mozillafestival.org to redirect to https://app.mozillafestival.org/#_spaces ? If it's the former it will be complicated to do due to the current app setup (I can be technical if you'd like to know more).

**Comment by edrushka** [comment]
Here is Mark's request. @xmatthewx can you help?

---

This is a nit but important:

Can ...
https://app.mozillafestival.org

... default to the /#_spaces content rather than the schedule / list of times? And then create #_schedule?

We're sending a bunch of traffic here, first contact should tell people story of what's happening.

**Comment by xmatthewx** [comment]
Okay. We discussed. @mmmavis will look to set it up like so: 
 - pre and post-festival, the app will default to Spaces view
 - during festival, app will show the current day
 - logo in header will link to the schedule view, or follow same pattern above if that's non-trivial to implement. no need to make extra work

**Comment by edrushka** [comment]
Great. Please ping me when this is done and I will let Mark know. Thanks for helping me with this request 😊

**Comment by mmmavis** [comment]
@edrushka @xmatthewx 

This is on staging now: https://mozfest-app-2016.mofostaging.net/ . I'm pushing it to production now.

### Pre & Post MozFest

- clicking on logo goes to Spaces Overview page
- clicking on the "schedule" nav link goes to Friday schedule view

### During MozFest

- clicking on logo goes to the schedule view of that day. (e.g., on Oct 29 Sat, clicking on logo will bring you to the Saturday schedule view)
- clicking on the "schedule" nav link goes to the schedule view of that day.

**Comment by xmatthewx** [comment]
Looks good. Thanks for building. Let's remember to confirm its working first thing on Fri and Sat.
